# fly.toml app configuration file
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

# The following fields are mandatory, but may be set by `flyctl launch`.
# app = ""
# primary_region = ""

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/go"]

[env]
  REDIRECTOR_CONFIG = "/app/config.json"

[metrics]
  port = 9091
  path = "/metrics"

[http_service]
  internal_port = 8080
  force_https = false
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  grace_period = "5s"
  interval = "10s"
  method = "GET"
  timeout = "5s"
  path = "/"

[http_service.checks.headers]
  Host = "health-check.internal"

[[files]]
  guest_path = "/app/config.json"
  local_path = "config.json"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
