name: Deploy to Fly.io

on:
  workflow_run:
    workflows:
      - Go Build & Test
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    concurrency: deploy-group
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - uses: actions/checkout@v3
    - uses: superfly/flyctl-actions/setup-flyctl@master
      with:
        version: '0.2.18'
    - name: Deploy
      run: flyctl deploy --remote-only --verbose
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion != 'success' }}
    steps:
    - name: Record non-deployment
      env:
        WORKFLOW: ${{ github.event.workflow_run.name }}
        CONCLUSION: ${{ github.event.workflow_run.conclusion }}
        RERUN_URL: ${{ github.event.workflow_run.rerun_url }}
        WORKFLOW_LOGS: ${{ github.event.workflow_run.logs_url }}
        WORKFLOW_URL: ${{ github.event.workflow_run.url }}
      run: |
        cat <<EOF >> $GITHUB_STEP_SUMMARY
        ### :warning: [$WORKFLOW]($WORKFLOW_URL) concluded with $CONCLUSION
        echo Re-run: $RERUN_URL
        echo Logs:   $WORKFLOW_LOGS
        EOF
